### ISSUE TITLE
Validate username and password on frontend

### ISSUE THREAD

**Issue by I-Smith** [kgost/doodle-chat#13]
# Task
- Require password to be 6 or more characters in length, must match with confirm password field
- Require username to be unique, make call to backend to check
- Submit button should start disabled and be enabled when all criteria have been met
- Use global boolean variables for each of the three conditions and set them to true or false in keypress listeners
- Use a normal function to disable or enable the submit button based on the three boolean variables. Call this function at the end of the keypress listeners
- For an example on making an ajax call to the server with jquery, look at the register submission code, will be similar to that but instead of using "method: 'post'" it should use get and the url should be '/api/userUniqueness/' + <value of username>. The .done and .fail code should be the same
- For the password and confirm password keypress listeners check that they are equal on both and set the boolean acordingly
- To show the user what the problem is, use https://getbootstrap.com/docs/4.0/components/alerts/ . Place an alert above each input and hide them initially. Then unhide them and fill them with the appropriate message from the keypress listeners

**Comment by damessic** [comment]
Completed username and password verification
