### ISSUE TITLE
Refactor app.js into multiple route files (DO THIS BEFORE ANYTHING ELSE!!!!!!!!!!!!!!)

### ISSUE THREAD

**Issue by kgost** [kgost/doodle-chat#27]
# Task
- Seperate out the routes in app.js into multiple folders based on their path and then in app.js require them and attach them to app using app.use('<base of route>', <required file>)
- When separating express.Router() must be used instead of app

**Comment by I-Smith** [comment]
31c7549aee60261e729a16168a922753c2f43948
